// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: type=lint, directives_ordering

import 'animation/animation_state_component.jge.dart' as _c0;
import 'audio/audio_source_component.jge.dart' as _c1;
import 'audio/audio_stream_component.jge.dart' as _c2;
import 'camera/camera_follow_component.jge.dart' as _c3;
import 'core/transform_component.jge.dart' as _c4;
import 'core/velocity_component.jge.dart' as _c5;
import 'effects/effect_component.jge.dart' as _c6;
import 'gameplay/health_component.jge.dart' as _c7;
import 'gameplay/lifetime_component.jge.dart' as _c8;
import 'gameplay/tag_component.jge.dart' as _c9;
import 'hierarchy/children_component.jge.dart' as _c10;
import 'hierarchy/parent_component.jge.dart' as _c11;
import 'input/input_component.jge.dart' as _c12;
import 'input/joystick_input_component.jge.dart' as _c13;
import 'input/simple_movement_component_editor.jge.dart' as _c14;
import 'physics/distance_joint_component_editor.jge.dart' as _c15;
import 'physics/physics_body_capsule_component.jge.dart' as _c16;
import 'physics/physics_body_chain_component.jge.dart' as _c17;
import 'physics/physics_body_circle_component.jge.dart' as _c18;
import 'physics/physics_body_polygon_component.jge.dart' as _c19;
import 'physics/physics_body_rectangle_component.jge.dart' as _c20;
import 'physics/physics_body_rounded_rect_component.jge.dart' as _c21;
import 'physics/physics_body_segment_component.jge.dart' as _c22;
import 'physics/physics_sensor_capsule_component.jge.dart' as _c23;
import 'physics/physics_sensor_circle_component.jge.dart' as _c24;
import 'physics/physics_sensor_rectangle_component.jge.dart' as _c25;
import 'physics/prismatic_joint_component_editor.jge.dart' as _c26;
import 'physics/weld_joint_component_editor.jge.dart' as _c27;
import 'physics/wheel_joint_component_editor.jge.dart' as _c28;
import 'rendering/capsule_component.jge.dart' as _c29;
import 'rendering/circle_component.jge.dart' as _c30;
import 'rendering/line_component.jge.dart' as _c31;
import 'rendering/polygon_component.jge.dart' as _c32;
import 'rendering/rectangle_component.jge.dart' as _c33;
import 'rendering/sprite_component.jge.dart' as _c34;
import 'ui/button_component.jge.dart' as _c35;
import 'ui/circular_progress_component.jge.dart' as _c36;
import 'ui/linear_progress_component.jge.dart' as _c37;
import 'ui/text_component.jge.dart' as _c38;
import 'ui/ui_catalog_component.jge.dart' as _c39;

void registerAllEditorCustomComponents() {
  _c0.registerGeneratedCustomComponents();
  _c1.registerGeneratedCustomComponents();
  _c2.registerGeneratedCustomComponents();
  _c3.registerGeneratedCustomComponents();
  _c4.registerGeneratedCustomComponents();
  _c5.registerGeneratedCustomComponents();
  _c6.registerGeneratedCustomComponents();
  _c7.registerGeneratedCustomComponents();
  _c8.registerGeneratedCustomComponents();
  _c9.registerGeneratedCustomComponents();
  _c10.registerGeneratedCustomComponents();
  _c11.registerGeneratedCustomComponents();
  _c12.registerGeneratedCustomComponents();
  _c13.registerGeneratedCustomComponents();
  _c14.registerGeneratedCustomComponents();
  _c15.registerGeneratedCustomComponents();
  _c16.registerGeneratedCustomComponents();
  _c17.registerGeneratedCustomComponents();
  _c18.registerGeneratedCustomComponents();
  _c19.registerGeneratedCustomComponents();
  _c20.registerGeneratedCustomComponents();
  _c21.registerGeneratedCustomComponents();
  _c22.registerGeneratedCustomComponents();
  _c23.registerGeneratedCustomComponents();
  _c24.registerGeneratedCustomComponents();
  _c25.registerGeneratedCustomComponents();
  _c26.registerGeneratedCustomComponents();
  _c27.registerGeneratedCustomComponents();
  _c28.registerGeneratedCustomComponents();
  _c29.registerGeneratedCustomComponents();
  _c30.registerGeneratedCustomComponents();
  _c31.registerGeneratedCustomComponents();
  _c32.registerGeneratedCustomComponents();
  _c33.registerGeneratedCustomComponents();
  _c34.registerGeneratedCustomComponents();
  _c35.registerGeneratedCustomComponents();
  _c36.registerGeneratedCustomComponents();
  _c37.registerGeneratedCustomComponents();
  _c38.registerGeneratedCustomComponents();
  _c39.registerGeneratedCustomComponents();
}
